### ISSUE TITLE
CUDA out of memory on running 11-bert-finetune-classification.ipynb

### ISSUE THREAD

**Issue by ACodingfreak** [datanizing/oreilly-finetuning-llm#1]
Hi,

I am trying to execute below notebook in a A30 GPU with 24GB of VRAM same as RTX 4090.

11-bert-finetune-classification.ipynb

For some strange reasons I am running out of memory in cuda as shown below. I tried restarting the kernel before running the notebook where nvidia-smi shows 100% memory available and no process in running state.

```
--------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[18], line 33
     30 model.zero_grad()        
     32 # forward pass (predict data)
---> 33 res = model(b_input_ids, 
     34                      token_type_ids=None, 
     35                      attention_mask=b_input_mask, 
     36                      labels=b_labels)
     38 # calculate and accumulate loss
     39 total_train_loss += res.loss.item()

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1775](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1774), in Module._wrapped_call_impl(self, *args, **kwargs)
   1773     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1774 else:
-> 1775     return self._call_impl(*args, **kwargs)

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1786](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1785), in Module._call_impl(self, *args, **kwargs)
   1781 # If we don't have any hooks, we want to skip the rest of the logic in
   1782 # this function, and just call forward.
   1783 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1784         or _global_backward_pre_hooks or _global_backward_hooks
   1785         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1786     return forward_call(*args, **kwargs)
   1788 result = None
   1789 called_always_called_hooks = set()

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:1187](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=1186), in ModernBertForSequenceClassification.forward(self, input_ids, attention_mask, sliding_window_mask, position_ids, inputs_embeds, labels, indices, cu_seqlens, max_seqlen, batch_size, seq_len, output_attentions, output_hidden_states, return_dict, **kwargs)
   1184 if attention_mask is None:
   1185     attention_mask = torch.ones((batch_size, seq_len), device=device, dtype=torch.bool)
-> 1187 outputs = self.model(
   1188     input_ids=input_ids,
   1189     attention_mask=attention_mask,
   1190     sliding_window_mask=sliding_window_mask,
   1191     position_ids=position_ids,
   1192     inputs_embeds=inputs_embeds,
   1193     indices=indices,
   1194     cu_seqlens=cu_seqlens,
   1195     max_seqlen=max_seqlen,
   1196     batch_size=batch_size,
   1197     seq_len=seq_len,
   1198     output_attentions=output_attentions,
   1199     output_hidden_states=output_hidden_states,
   1200     return_dict=return_dict,
   1201 )
   1202 last_hidden_state = outputs[0]
   1204 if self.config.classifier_pooling == "cls":

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1775](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1774), in Module._wrapped_call_impl(self, *args, **kwargs)
   1773     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1774 else:
-> 1775     return self._call_impl(*args, **kwargs)

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1786](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1785), in Module._call_impl(self, *args, **kwargs)
   1781 # If we don't have any hooks, we want to skip the rest of the logic in
   1782 # this function, and just call forward.
   1783 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1784         or _global_backward_pre_hooks or _global_backward_hooks
   1785         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1786     return forward_call(*args, **kwargs)
   1788 result = None
   1789 called_always_called_hooks = set()

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:869](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=868), in ModernBertModel.forward(self, input_ids, attention_mask, sliding_window_mask, position_ids, inputs_embeds, indices, cu_seqlens, max_seqlen, batch_size, seq_len, output_attentions, output_hidden_states, return_dict)
    866 if output_hidden_states:
    867     all_hidden_states = all_hidden_states + (hidden_states,)
--> 869 layer_outputs = encoder_layer(
    870     hidden_states,
    871     attention_mask=attention_mask,
    872     sliding_window_mask=sliding_window_mask,
    873     position_ids=position_ids,
    874     cu_seqlens=cu_seqlens,
    875     max_seqlen=max_seqlen,
    876     output_attentions=output_attentions,
    877 )
    878 hidden_states = layer_outputs[0]
    879 if output_attentions and len(layer_outputs) > 1:

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/modeling_layers.py:94](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/modeling_layers.py#line=93), in GradientCheckpointingLayer.__call__(self, *args, **kwargs)
     91         logger.warning_once(message)
     93     return self._gradient_checkpointing_func(partial(super().__call__, **kwargs), *args)
---> 94 return super().__call__(*args, **kwargs)

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1775](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1774), in Module._wrapped_call_impl(self, *args, **kwargs)
   1773     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1774 else:
-> 1775     return self._call_impl(*args, **kwargs)

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1786](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1785), in Module._call_impl(self, *args, **kwargs)
   1781 # If we don't have any hooks, we want to skip the rest of the logic in
   1782 # this function, and just call forward.
   1783 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1784         or _global_backward_pre_hooks or _global_backward_hooks
   1785         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1786     return forward_call(*args, **kwargs)
   1788 result = None
   1789 called_always_called_hooks = set()

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:542](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=541), in ModernBertEncoderLayer.forward(self, hidden_states, attention_mask, sliding_window_mask, position_ids, cu_seqlens, max_seqlen, output_attentions)
    532 def forward(
    533     self,
    534     hidden_states: torch.Tensor,
   (...)    540     output_attentions: Optional[bool] = False,
    541 ) -> torch.Tensor:
--> 542     attn_outputs = self.attn(
    543         self.attn_norm(hidden_states),
    544         attention_mask=attention_mask,
    545         sliding_window_mask=sliding_window_mask,
    546         position_ids=position_ids,
    547         cu_seqlens=cu_seqlens,
    548         max_seqlen=max_seqlen,
    549         output_attentions=output_attentions,
    550     )
    551     hidden_states = hidden_states + attn_outputs[0]
    552     mlp_output = (
    553         self.compiled_mlp(hidden_states)
    554         if self.config.reference_compile
    555         else self.mlp(self.mlp_norm(hidden_states))
    556     )

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1775](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1774), in Module._wrapped_call_impl(self, *args, **kwargs)
   1773     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1774 else:
-> 1775     return self._call_impl(*args, **kwargs)

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py:1786](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/torch/nn/modules/module.py#line=1785), in Module._call_impl(self, *args, **kwargs)
   1781 # If we don't have any hooks, we want to skip the rest of the logic in
   1782 # this function, and just call forward.
   1783 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1784         or _global_backward_pre_hooks or _global_backward_hooks
   1785         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1786     return forward_call(*args, **kwargs)
   1788 result = None
   1789 called_always_called_hooks = set()

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:500](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=499), in ModernBertAttention.forward(self, hidden_states, output_attentions, **kwargs)
    497 else:
    498     qkv = qkv.view(bs, -1, 3, self.num_heads, self.head_dim)
--> 500 attn_outputs = MODERNBERT_ATTENTION_FUNCTION[self.config._attn_implementation](
    501     self,
    502     qkv=qkv,
    503     rotary_emb=self.rotary_emb,
    504     local_attention=self.local_attention,
    505     bs=bs,
    506     dim=self.all_head_size,
    507     output_attentions=output_attentions,
    508     **kwargs,
    509 )
    510 hidden_states = attn_outputs[0]
    511 hidden_states = self.out_drop(self.Wo(hidden_states))

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:410](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=409), in sdpa_attention_forward(module, qkv, attention_mask, sliding_window_mask, position_ids, local_attention, bs, dim, **_kwargs)
    408 query, key, value = qkv.transpose(3, 1).unbind(dim=2)
    409 # query, key, value: [batch_size, heads, seq_len, head_dim]
--> 410 query, key = apply_rotary_pos_emb(query, key, cos, sin)
    412 if local_attention != (-1, -1):
    413     attention_mask = sliding_window_mask

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:310](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=309), in apply_rotary_pos_emb(q, k, cos, sin, position_ids, unsqueeze_dim)
    308 cos = cos.unsqueeze(unsqueeze_dim)
    309 sin = sin.unsqueeze(unsqueeze_dim)
--> 310 q_embed = (q * cos) + (rotate_half(q) * sin)
    311 k_embed = (k * cos) + (rotate_half(k) * sin)
    312 return q_embed, k_embed

File [~/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py:285](http://10.30.0.105:8888/home/ipi/anaconda3/envs/aiFineTuning/lib/python3.11/site-packages/transformers/models/modernbert/modeling_modernbert.py#line=284), in rotate_half(x)
    283 x1 = x[..., : x.shape[-1] // 2]
    284 x2 = x[..., x.shape[-1] // 2 :]
--> 285 return torch.cat((-x2, x1), dim=-1)

OutOfMemoryError: CUDA out of memory. Tried to allocate 48.00 MiB. GPU 0 has a total capacity of 23.50 GiB of which 33.25 MiB is free. Including non-PyTorch memory, this process has 23.46 GiB memory in use. Of the allocated memory 23.17 GiB is allocated by PyTorch, and 20.90 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by datanizing** [comment]
Sorry for the late reply.

Maybe it is an issue with the datatypes? Can you try another model which does not use bfloat16 (like the original https://huggingface.co/google-bert/bert-base-uncased

**Comment by ACodingfreak** [comment]
bert-base-uncased worked for me.

**Comment by datanizing** [comment]
OK, then I suspect that your GPU cannot efficiently handle ModernBERT and reserves too much RAM for that. Thanks for reporting!

**Comment by ACodingfreak** [comment]
> OK, then I suspect that your GPU cannot efficiently handle ModernBERT and reserves too much RAM for that. Thanks for reporting!

Interesting as I am using NVIDIA A30 GPU which is Ampere class with 24GB of memory.
